### ISSUE TITLE
not responsive, the gpay icon covers the entire screen in mobile

### ISSUE THREAD

**Issue by salus-sage** [anamritraj/livecovid.in-webapp#1]
![Screenshot_20200406-153050](https://user-images.githubusercontent.com/6399323/78546797-90e36e80-77ed-11ea-8d82-d790775e4bb8.png)

Browser: firefox and chrome on android

**Comment by anamritraj** [comment]
Can you try opening it in a private window? Maybe it is possible that the CSS style corresponding to that element has not loaded (Although highly unlikely). 

If that doesn't work, I will change the styles more time to bust the cache.

**Comment by salus-sage** [comment]
same even in private browser, to debug i checked on laptop also, same in responsive debug mode. 
I tried to set width to `.floating-actions` which may fix the issue. but something funny happened after i unset the width, the icon sizes didn't resume to original full screen.

so you might be right, because the element starts as hidden or some reason ur styles to that elements not getting applied
### set width
![Screenshot (170)](https://user-images.githubusercontent.com/6399323/78703977-c80a6a80-7928-11ea-8b83-c7e37f5bb136.png)

### Unset Width
![Screenshot (171)](https://user-images.githubusercontent.com/6399323/78703996-d0fb3c00-7928-11ea-8a55-c4a22b925b74.png)

**Comment by anamritraj** [comment]
Interesting! This looks like a genuine problem. I will try to reproduce this using different browsers and phones. Thanks for taking a look at this.

**Comment by anamritraj** [comment]
Got it in Firefox Developer Edition! Its strange it doesn't happen in other browsers. Again, thanks for reporting this.

![Screen Shot 2020-04-07 at 23 56 40](https://user-images.githubusercontent.com/11889942/78705652-6e576f80-792b-11ea-8e24-347782ab94ae.png)
