### ISSUE TITLE
Show state-wise testing stats

### ISSUE THREAD

**Issue by anamritraj** [anamritraj/livecovid.in-webapp#5]
- Use [this API](https://api.covid19india.org/state_test_data.json) to show the testing details for individual states.
- If you need data in a different format or filtered, that can be arranged as this has a backend repo made using express.js
- Preferred place would be the state-wise table, but open to suggestions.

**Comment by AkshayAlenchery** [comment]
Do you want it as a new column inside the table?

**Comment by AkshayAlenchery** [comment]
<img width="625" alt="Screenshot 2020-04-23 at 7 51 48 PM" src="https://user-images.githubusercontent.com/28904556/80110163-01cfa800-859c-11ea-839f-d5fd8f0dd07d.png">

Would this be fine?

**Comment by anamritraj** [comment]
Yeah looks good! If you can add some colors that would be awesome but still this looks great!

**Comment by anamritraj** [comment]
You can use this API, https://api.livecovid.in/api/states/testing
It will make you life easy

**Comment by AkshayAlenchery** [comment]
Yes.

**Comment by anamritraj** [comment]
Closed in #14.

Thanks @AkshayAlenchery 🚀 I will add you as a collaborator in the backend repo.
