### ISSUE TITLE
Show percentage of affected people

### ISSUE THREAD

**Issue by anamritraj** [anamritraj/livecovid.in-webapp#6]
<img width="1538" alt="Screenshot 2020-04-08 at 12 33 34 AM" src="https://user-images.githubusercontent.com/11889942/78709042-a44b2280-7930-11ea-8079-dd27c41dca7d.png">

- We can add percentage of people affected for following: 
   - Confirmed - % of people confirmed of tested (confirmed / tested)
   - Recovered - % of people recovered of Confirmed (recovered / confirmed)
   - Deceased - % of people deceased of Confirmed (deceased / confirmed)

Open to suggestions if you have a better way of calculating the percentages which is more closer to actual situation than just an empirical guess.

**Comment by AkshayAlenchery** [comment]
So you will display % instead of count?
With the data you have, I guess the logic you put forward is accurate.

**Comment by arhamshah** [comment]
For Confirmed cases percentage would go by confirmed/population.

**Comment by anamritraj** [comment]
Well this is would represent the % of affected people out of total tested people.

What you are saying also makes sense. But that value would be too small. Like 0.0000something %. And that is better represented as cases/million which is already implemented country and state wise.

**Comment by arhamshah** [comment]
Yes that would be even better

**Comment by arhamshah** [comment]
Assign this task to me

**Comment by anamritraj** [comment]
@ShraddhaJ11 are you working on this?

**Comment by ShraddhaJ11** [comment]
Yes , I am working on it

**Comment by anamritraj** [comment]
Closed in #28
